wicket:
  core:
    settings:
      general:
        configuration-type: development
      debug:
        enabled: true
        component-use-check: true
        development-utilities-enabled: true
server:
  port: 8091
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dshs?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: Aljoshka82
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  file:
    path: logs
external:
  development:
    devutils:
      statelesschecker:
        enabled: true
      interceptor:
        enable-live-sessions-page: true
      diskstorebrowser:
        enabled: true
    wicketsource:
      enabled: true