server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dshs?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: Aljoshka82
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    root:           INFO
    irl:
      lyit:
        DublinSmartHouseSearch: INFO
  pattern:
    file: '%d{yyyy.MM.dd HH:mm:ss} %-5level [%thread] %logger{15} - %msg%n'
    console: '%d{yyyy.MM.dd HH:mm:ss} %-5level [%thread] %logger{15} - %msg%n'
  file:
    path: logs
external:
  development:
    devutils:
      statelesschecker:
        enabled: true
      interceptor:
        enable-live-sessions-page: true
      diskstorebrowser:
        enabled: true
    wicketsource:
      enabled: true
credentials:
  googleApiKey: AIzaSyBDoe7QtoHzRpGj9RX52T4mzSjkaXzx8lo
  travelTimeApiKey: 390add03321ba0b75ceda50d6a0baa82
  travelTimeApplicationId: a8605824


