server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dshs?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: Aljoshka82
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  file:
    path: logs